### ISSUE TITLE
[Docs] How to run without a project

### ISSUE THREAD

**Issue by BojanKogoj** [ng-doc/ng-doc#105]
### Description

I'm trying to set it up in a UI library that doesn't have any projects (only has one `"projectType": "library"`).
Builder changed build configuration, but there is no serve options. Even if I add it manually, it will throw an error, since it requires [`main.ts`](https://github.com/ng-doc/ng-doc/blob/main/libs/builder/helpers/create-builder-context.ts#L21) which obviously doesn't exist (we used Storybook so far). 

Is documentation missing things or does it not support what I would like

**Comment by skoropadas** [comment]
Hi, yes, Storybook creates the application for you and runs it, while this library requires you to have a separate Angular application that you will use for your documentation. This is done for greater customization so that you have maximum flexibility and can tailor everything to your liking.

So, yes, to use this library, you need to have a separate application.

**Comment by skoropadas** [comment]
I'll close the issues, if you have any other questions feel free to reopen
