### ISSUE TITLE
[Feature] Configuration to allow demos to have sub-routes

### ISSUE THREAD

**Issue by gpaucot** [ng-doc/ng-doc#106]
### Description

Context: Documenting the master/detail pattern, the demo needs routing.

Sub-routes added to a page are shown in a dialog, it would be nice to disable that on a certain config.

### Proposed solution

Conditionally add the _ng-doc-dialog-outlet_ in _/libs/app/components/page/page.component.html_
```diff
-<ng-doc-dialog-outlet [config]="{ width: '100vw', height: '100vh' }">
+<ng-doc-dialog-outlet *ngIf="rootPage.page?.showChildRoutesInDialog ?? true" [config]="{ width: '100vw', height: '100vh' }">
	<div class="ng-doc-fullscreen-wrapper">
		<router-outlet></router-outlet>
	</div>
</ng-doc-dialog-outlet>
```

I can contribute :slightly_smiling_face: I would also love some suggestions for a better name for "showChildRoutesInDialog" 

### Alternatives considered

Allowing to specify an alternative to NgDocPageComponent in the configuration

**Comment by skoropadas** [comment]
Hey, thank you for the ticket! If I understand correctly, you want to place your custom `router-outlet` in your demo component to display child routes, is that correct?

**Comment by gpaucot** [comment]
Yes exactly. In my case, the demo shows a master table, when I click on a row, I navigate to the detail view of that row.

**Comment by skoropadas** [comment]
@gpaucot I actually thought about it when creating the current solution. The only issue is that in such a case, you can have only one demo on the page that has a `router-outlet`, otherwise, it may not work correctly. That's why I implemented it as a full-screen modal window.

But if it's ok I think you can name this property as "disableFullscreenRoutes." "Disable" because it's enabled by default, and we wouldn't want to introduce breaking changes. "FullscreenRoutes" because that's the property you pass to the `NgDocActions.demo` function.

I also think it's a good idea to implement it as a parameter in the "data" field for the route configuration. This should make it easier, and you can easily access it using `ActivatedRoute` in the PageComponent. So if you want, you can try to implement it, and then we can see how it works :)

**Comment by gpaucot** [comment]
It is working well :slightly_smiling_face:  could you give me some pointers to where i can put some documentation and some unit tests ?

https://github.com/gpaucot/ng-doc/commit/cd4ef92528806ece281013fa625911a571a4c2dd

**Comment by skoropadas** [comment]
@gpaucot Thank you very much, looks good! I think we can use a blockquote for the [demo](https://github.com/ng-doc/ng-doc/blob/main/apps/ng-doc/docs/guides/demo/index.md) and [demo pane](https://github.com/ng-doc/ng-doc/blob/main/apps/ng-doc/docs/guides/demo-pane/index.md) pages (both have an example with fullscreen), where we can explicitly mention that this behavior can be turned off using this parameter.

You can also use a shared template to avoid duplicating this bloquote, as I did [here](https://github.com/ng-doc/ng-doc/tree/main/apps/ng-doc/docs/shared)

**Comment by gpaucot** [comment]
@skoropadas Done, can you give a feedback on the doc ? :slightly_smiling_face: https://github.com/gpaucot/ng-doc/commit/7ddf5fc63ca1cd8c5d4b34aac88a5552dcb73673

**Comment by skoropadas** [comment]
@gpaucot looks great big thanks! Could you create a PR?

**Comment by skoropadas** [comment]
@gpaucot sry 16.18.0 was released by my mistake, you can use 16.17.0 instead

**Comment by gpaucot** [comment]
@skoropadas I understand, this specific ticket isn't present in 16.17.0 though. I will do without it and reserve the master/detail case for when we migrate to v17 :muscle:

**Comment by skoropadas** [comment]
@gpaucot  are you sure? because I see this feature in 16.17.0
<img width="1222" alt="image" src="https://github.com/ng-doc/ng-doc/assets/20700969/93328be0-1aa2-45f3-8c5c-2f360340b7f8">

**Comment by gpaucot** [comment]
Thanks !
