### ISSUE TITLE
[Bug] allowSyntheticDefaultImports not added to tsconfig when using automatic installation

### ISSUE THREAD

**Issue by tayambamwanza** [ng-doc/ng-doc#111]
### Is this a regression?

I don't know

### Description

When I ran ```ng add @ng-doc/add```

I found that I had an error message for @ng-doc/generated: Module is not listed in package.json dependencies 

I looked at manual installation and found that allowSyntheticDefaultImports:true was not added to tsconfig compiler options.

### Please provide the exception or error you saw

```true
Module is not listed in package.json dependencies
```

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

v18.13.0

**Comment by skoropadas** [comment]
I have fixed several issues in the `@ng-doc/add` package caused by the latest update. Now everything should work fine in version 17.1.2. If you still have this issue, feel free to reopen the ticket!

**Comment by tayambamwanza** [comment]
@skoropadas thank you, I misdiagnoised this problem because I was looking in the wrong tsconfig.

But I do think there is another problem, I didn't have a baseUrl in my tsconfig, I think my angular generated without one, do you think maybe there should also be a note in installation for that.

That's the last problem, otherwise automatic installation works, I can open a new issue if you want.

Btw I generated the app with the new --ssr flag so maybe that's why my setup isn't 100%

**Comment by skoropadas** [comment]
@tayambamwanza SSR might be the cause, I haven't tested migrations and the ability to run the application with SSR enabled because it's a new feature. However, I believe it's worth addressing this as a priority, as it makes a lot of sense for a documentation application.

Yes, please create a new ticket for supporting automatic installation in applications with SSR enabled. And thank you for your help! :)
