### ISSUE TITLE
[Bug] Getting Peer dependency issue while adding to angular 16 project

### ISSUE THREAD

**Issue by pankaj-mishra1** [ng-doc/ng-doc#120]
### Is this a regression?

I don't know

### Description

I am trying to add this to angular 16 app but its throwing error

### Please provide the exception or error you saw

```true
npm ERR! While resolving: testdoc@0.0.0
npm ERR! Found: @angular/common@15.2.10
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^15.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^17.0.0 || ^18.0.0" from @angular/cdk@17.0.4
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@">=17.0.0" from @ng-doc/app@17.2.0
npm ERR!   node_modules/@ng-doc/app
npm ERR!     @ng-doc/app@"17.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### OS

Windows

### Browser

None

### Node version

18.15

### Anything else?

NA

**Comment by skoropadas** [comment]
Hi, yes, the project is heavily dependent on the major version of Angular. With each new version of Angular, adjustments are required that break backward compatibility. That's why each major version of NgDoc is tied to a corresponding major version of Angular.

If for some reason you cannot use Angular 17, you can install version 16 of NgDoc using `ng add @ng-doc/add@16.17.0`.

I can still fix a bug in the previous version, but new releases will always be available only for the latest major version.

**Comment by pankaj-mishra1** [comment]
When trying with version 16 getting peer dependency error.

While resolving: ui-doc@0.0.0
npm ERR! Found: @angular/common@16.2.12
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^16.2.0" from the root project
npm ERR!   peer @angular/common@">=16.0.0" from @ng-doc/app@16.0.0
npm ERR!   node_modules/@ng-doc/app
npm ERR!     @ng-doc/app@"16.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^17.0.0 || ^18.0.0" from @angular/cdk@17.0.4
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@">=16.0.0" from @ng-doc/app@16.0.0
npm ERR!   node_modules/@ng-doc/app
npm ERR!     @ng-doc/app@"16.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by skoropadas** [comment]
@pankaj-mishra1 could you share your package.json file? I'll try to reproduce the issue

**Comment by pankaj-mishra1** [comment]
sure 
[package.json](https://github.com/ng-doc/ng-doc/files/13751191/package.json)

**Comment by skoropadas** [comment]
Ok, I got it, it happens because major version of `@angular/cdk` is unlocked in NgDoc@16, so it's trying to install `@angular/cdk17` that depends on `@angular/*@17`. I'll fix it, and to make it work on your side you can do the following:

- add `@angular/cdk@16` package to you dependencies
- remove `package-lock.json`
- remove `node_modules`
- install dependencies

so your list of dependencies should look like this:

```json
"dependencies": {
    "@angular/animations": "^16.2.1",
    "@angular/common": "^16.2.1",
    "@angular/compiler": "^16.2.1",
    "@angular/core": "^16.2.1",
    "@angular/cdk": "^16.2.1",
    "@angular/forms": "^16.2.1",
    "@angular/platform-browser": "^16.2.1",
    "@angular/platform-browser-dynamic": "^16.2.1",
    "@angular/router": "^16.2.1",
    "@ng-doc/app": "16.15.1",
    "@ng-doc/builder": "16.15.1",
    "@ng-doc/core": "16.15.1",
    "@ng-doc/ui-kit": "16.15.1",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.10",
    "@angular/cli": "^16.2.10",
    "@angular/compiler-cli": "^16.2.10",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "ng-packagr": "^16.2.0",
    "typescript": "~5.1.3"
  }
```

**Comment by pankaj-mishra1** [comment]
Great!!. Thanks much for your help

**Comment by relu91** [comment]
Got it by this today with Angular 17, it seems that the lastest version still try to install @angular/cdk@18. Doing the steps above did solve the problem. Is this a bug or rather something that needs to be added to https://github.com/ng-doc/ng-doc/edit/main/apps/ng-doc/docs/getting-started/installation/index.md ?

**Comment by skoropadas** [comment]
@relu91 Thank you for mentioning it. I am trying not to block the major version of Angular packages so that you don't have to wait for the release of NgDoc when a new major version comes out.

But I would say this is a bug, but it's more likely caused by the delay of the NgDoc 18 version release. I simply didn't have time to prepare it, so I added support for Angular 18 to NgDoc 17 to avoid blocking those who want to upgrade. After the release of NgDoc 18, I will lock the major version of Angular packages and try to release a new version of NgDoc on time.
