### ISSUE TITLE
 Build directory do not have any index.html

### ISSUE THREAD

**Issue by pankaj-mishra1** [ng-doc/ng-doc#121]
I tried to build it locally and dist folder do not have any index.html file. Is it ok or let me know if I its expected. I need  to deploy the documentation in different server, so need step to deploy.

**Comment by skoropadas** [comment]
I don't think this is the expected behavior. NgDoc does not affect the Angular application build, it simply generates Angular components and routes based on your documentation before the build starts. After that, it triggers the Angular builder, so everything should work the same as in a project without NgDoc.

You can check if your build is working by installing a local server (`npm i -D serve`) and running it in your `dist` folder with the `serve` command to ensure that your application is functioning.

This issue could also be related to the [following problem](https://github.com/angular/angular-cli/issues/15175#issuecomment-517260507).

**Comment by pankaj-mishra1** [comment]
Thanks it was same issue [https://github.com/angular/angular-cli/issues/15175#issuecomment-517260507](url).  Once again thanks much!!  Let me know if we can share coffee someday!!!!
