### ISSUE TITLE
[Bug] NgDocActions doesn't display demo

### ISSUE THREAD

**Issue by wadie** [ng-doc/ng-doc#122]
### Is this a regression?

I don't know

### Description

I'm on Angular 17, when using NgDocActions.demo I only get `{}` as output.
Here's my code:

index.md:
```md
# {{ NgDocPage.title }}

{{ NgDocActions.demo("DottedComponent") }}

```

ng-doc.page.ts:
```ts
import { NgDocPage } from '@ng-doc/core';
import ExamplesCategory from '../ng-doc.category';
import { DottedComponent } from './dotted.component';

const DottedPage: NgDocPage = {
  title: `Dotted loader`,
  mdFile: './index.md',
  category: ExamplesCategory,
  order: 1,
  demos: { DottedComponent },
};

export default DottedPage;
```

dotted.component.ts:
```ts
import { Component } from '@angular/core';

@Component({
  selector: 'dotted-demo',
  standalone: true,
  template: `Content`,
})
export class DottedComponent {}
```

### OS

Unix (Linux, macOS, etc.)

### Browser

Firefox

### Node version

v19.1.0

**Comment by skoropadas** [comment]
Hey, thanks for the ticket! Could you please create a repository where this behavior can be reproduced? I just couldn't reproduce this issue in a clean or existing project

**Comment by wadie** [comment]
Thank you for your quick reply.

You can find the code here: https://github.com/wadie/ngx-gooey/tree/main/docs/src/app/examples/dotted

**Comment by skoropadas** [comment]
Great, thank you! I found the issue. There were errors in the browser console, and you need to add `HttpClientModule` to your `AppModule` because NgDoc uses it to load icons. Due to this, some functionality simply stopped working, and that's why the demo wasn't loading.

I also noticed another bug: even with `HttpClientModule`, the icons weren't loading, and it was impossible to refresh a page in any category using F5. Probably, you accidentally deleted `<base href="/">` in your `index.htm`l. You should add it back, and then everything should start working.

I also recommend using your library from the current repository using TypeScript `paths` instead of installing it from `npm`. This way, you can take advantage of other features, such as playgrounds.
