### ISSUE TITLE
[Feature] Better automatic recognition of input signals for playground

### ISSUE THREAD

**Issue by safraja** [ng-doc/ng-doc#137]
### Description

It would be nice if ngdoc was better at recognizing input signals for playground automatically. I've tried several different ways how to define input signals and most of them are't recognized (no controls are created for them). Below is a list of test inputs I tried, `@Input` mostly work great, but signal inputs not so much:

```js
type MyType = 'aaa' | 'bbb';

// Works:
testSuccess1 = input<string>('');
testSuccess2 = input('');
@Input() testSuccess3: string;
@Input() testSuccess4: 'aaa' | 'bbb';
@Input() testSuccess5?: 'aaa' | 'bbb';
@Input() testSuccess6 = '';
@Input() testSuccess7?: MyType;
@Input() testSuccess8: MyType = 'bbb';


// Doesn't work:
testFail1 = input<string>();
testFail2 = input<'aaa' | 'bbb'>();
testFail3 = input<'aaa' | 'bbb'>('aaa');
testFail4 = input<MyType>();
testFail5 = input<MyType>('bbb');
@Input() testFail6?: string; // Not input signal,  but doesn't seem to be recognized correctly either
````

### Proposed solution

Improving the auto recognition to be able to recognize more ways in which input signals can be defined, so that the correct controls are generated for them. 

### Alternatives considered

Extend the documentation to include information which ways of defining input signals are supported and which ones ngdoc can't recognize.

**Comment by safraja** [comment]
In connection to this, I'd like some advice. Since the input signals weren't automatically recognized, I defined the controls manually in NgDocPlaygroundConfig.controls, but I failed to create a select control. Even though I used
```js
'size': { type: 'string', options: ['s', 'm', 'l', 'xl'] }
```
it generated normal text input, not select. I tried several different definitions I could think of, but none succeeded. 
Could you please advise me how to write it correctly so that I get a select control with options 's', 'm', 'l' and 'xl'?

**Comment by skoropadas** [comment]
Amazing research, thank you! I've fixed all the bugs you found, and I've also fixed the issue with the `controls` field. Now everything should work fine.

About your question:
You should use the name of your type alias as the `type` if you have it, because specifying the type as `string` makes NgDoc create a control for managing string types:
```
'size': { type: 'Size', options: ['s', 'm', 'l', 'xl'] }
```

Or if for any reason you don't have a separate type, you can also specify the type as `NgDocTypeAlias`, which is a general type used internally to manage all recognized type alias types that NgDoc can understand (this is not mentioned in the documentation, but I'll add an explanation later):
```
'size': { type: 'NgDocTypeAlias', options: ['s', 'm', 'l', 'xl'] }
```

**Comment by safraja** [comment]
Thanks very much for such a quick fix! You're right, everything seems to be working now, even the `controls` (in case I need to use it somewhere).

I have to say that so far I really like ngdoc and it's fantastic how quickly you're responding. Thanks again, if I run into any more problems I'll create another ticket. 🙂
