### ISSUE TITLE
[Bug] `@ng-doc/builder:dev-server`  Schema Validation Error When the `ngDoc` Propertiy is Provided

### ISSUE THREAD

**Issue by Char2sGu** [ng-doc/ng-doc#147]
### Is this a regression?

No

### Description

When the `ngDoc` option is provided in `@ng-doc/builder:application`, running `@ng-doc/builder:dev-server` will result in the following schema validation error:

```sh
char2s@REDMI-G:~/projects/demo-ng-doc$ ng serve
Error: Schema validation failed with the following errors:
  Data path "" must NOT have additional properties(ngDoc).
```

### OS

Unix (Linux, macOS, etc.)

### Browser

None

### Node version

v18.19.0

**Comment by skoropadas** [comment]
could you share your `angular.json` (or `project.json` if you are using NX)?

**Comment by TheNightmareX** [comment]
`ng version`:
```
Angular CLI: 17.3.3
Node: 18.19.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.3.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.3
@angular-devkit/build-angular   17.3.3
@angular-devkit/core            17.3.3
@angular-devkit/schematics      17.3.3
@angular/cli                    17.3.3
@schematics/angular             17.3.3
rxjs                            7.8.1
typescript                      5.4.3
zone.js                         0.14.4
```

**Comment by skoropadas** [comment]
Ah I see, probably it's gonna work if you move it under `configurations.[production | development]` section.

This is configured for each specific build type to provide more flexibility. For example, displaying or hiding certain pages for different builds. I use this to have a "Development" page where I can develop components in development mode.

By default, specifying the path to the configuration file is not mandatory. NgDoc searches for it starting from the directory of the file specified in the `browser` property of your `angular.json` configuration and ending at the root folder of the repository.

**Comment by TheNightmareX** [comment]
> probably it's gonna work if you move it under configurations.[production | development] section.
I tried that too, the same result.

I believe it is probably because that the extra `ngDoc` property is not removed before passing it to the underlying Angular builder.

**Comment by skoropadas** [comment]
> I tried that too, the same result. The resulting options should be the same, no matter where I put it.
> 
> I believe it is probably because that the extra `ngDoc` property is not removed from the options before passing it to the underlying Angular builder.

I'll check this on a clean Angular project and let you know!

> Aww this doesn't seem like an optimimal solution to me at all.. I believe it is acceptable to prioritize conventions over configurations within the project's source, e.g. the mandatory naming of `ng-doc.page.ts`, but definitely not a good idea to automatically search for the configuration file for the building process. The Angular building infrastructure is based on the configuration-oriented approach (everything is explicitly specified in `angular.json` / `project.json`), and I believe we should follow this convention to let the user explicitly specify the configuration.

Here's a slightly different logic: for the configuration file, we use the [cosmiconfig](https://github.com/cosmiconfig/cosmiconfig) library, which is a kind of standard approach for creating and loading configuration files. It's used by ESLint, Prettier, and other libraries that utilize configuration files. The file loading logic described above is used by cosmiconfig by default.

This approach is specifically used because as I said it's kind of standart and NgDoc is also used in monorepositories that may have multiple documentation projects but use a single builder configuration file, so it makes their lives easier.

In any case, this can be considered additional flexibility, as if you explicitly specify the path to the configuration file in your `angular.json`, NgDoc will only load that file or give an error if the path isn't specified. If the path to the configuration file isn't specified, cosmiconfig will try to find it. You can find this logic [here](https://github.com/ng-doc/ng-doc/blob/39f907d1a70159d7ec766cb3da36397d5deaf2b9/libs/builder/helpers/create-builder-context.ts#L21).

**Comment by TheNightmareX** [comment]
Ah I get your point, but still, here's another slightly different logic: Prettier and ESLint are kind of the fundamental tools for a repository, but the configuration file for NgDoc is to configure an Angular builder, which, by convention, should be explicitly configured through `angular.json` / `project.json`.

In the case of "multiple documentation projects using a single builder configuration file in a monorepo", I personally prefer to create a separate configuration file for each documentation project where the base configuration is extended.

projects/some-docs/ng-doc.config.js
```js
/**@type {import('@ng-doc/builder').NgDocConfiguration} */
module.exports = {
  ...require("../../ng-doc.base.config.js"),
};
```

project.json
```json
"ngDoc": { "config": "projects/some-docs/ng-doc.config.js" }
```

This follows a similar pattern as the tsconfig files, which is also specific to each project and extends the base tsconfig.

Overall, my point is that it feels unnatural to use the convention-based config file approach for an Angular builder, but there's no harm to keep both approaches. Writing just to discuss the different approaches, no changes requested.

**Comment by skoropadas** [comment]
@Char2sGu  I agree with your logic. I think we just see the NgDoc builder differently. You see it as an Angular builder that builds the application, while I see it as an Angular builder that integrates into the application's build process and runs a separate independent script alongside the Angular builder, which renders Angular components and is not dependent on the Angular ecosystem. Therefore, it's normal for me that this script accepts similar configurations; for me, it simply isn't something directly related to Angular ecosystem.

In any case, within this ticket, I'll fix the bug with the .js configuration if it exists, and I'll consider your suggestion in the next major version since it will definitely lead to additional breaking changes.

**Comment by Char2sGu** [comment]
Makes sense. I do understand that the builder inserts an extra build process before invoking the underling application builder, but it doesn't affect the fact that it is still an Angular builder, regardless how it works internally.

Anyway, I have no opinion against the current design since it supports both approaches. Look forward to the fix!

**Comment by Char2sGu** [comment]
I believe that this hack caused the problem:

https://github.com/ng-doc/ng-doc/blob/32d3e11f953a950e58c50067e839bacddd4b14ca/libs/builder/dev-server/index.ts#L43-L47

The schema validation seems to be based on the builder name.

**Comment by Char2sGu** [comment]
The custom dev-server of `@angular-builders/custom-esbuild` is a good example of how to fix it:

https://github.com/just-jeb/angular-builders/blob/dbf4d281a29c2f93d309bba0e155c3a22965130c/packages/custom-esbuild/src/dev-server/patch-builder-context.ts

You simply need another patch on `getTargetOptions`.

**Comment by skoropadas** [comment]
> I believe that this hack caused the problem:
> 
> https://github.com/ng-doc/ng-doc/blob/32d3e11f953a950e58c50067e839bacddd4b14ca/libs/builder/dev-server/index.ts#L43-L47
> 
> The schema validation seems to be based on the builder name.

Didn't know about this issues, I'll check it thanks 👍

**Comment by Char2sGu** [comment]
Btw, there is a developer-preview `forceEsBuild` option of the official dev-server builder:

https://github.com/angular/angular-cli/blob/4d27c38cd4ecdaf61b054c144b5c628c68b792b5/packages/angular_devkit/build_angular/src/builders/dev-server/builder.ts#L199-L220
