### ISSUE TITLE
[Feature] Support `.js` Version of Ng Doc Configuration File

### ISSUE THREAD

**Issue by Char2sGu** [ng-doc/ng-doc#148]
### Description

Personally I do not like the idea of using TypeScript files as configurations.

Using a CommonJS JavaScript file works fine for `@ng-doc/builder:application`, but is ignored by `@ng-doc/builder:dev-server`, although `@ng-doc/builder:dev-server` eventually fails after generating the files due to a schema validation error as mentioned in #147 

### Proposed solution

Support both `.js` and `.ts` configuration files.

### Alternatives considered

Actually, I've been wondering, why we should use a separate configuration file to configure the builder's behaviors.  
Most options in the configuration file are related only to the builder. For those options, simply using builder options seems to be more reasonable choice.  
For customization options, I would suggest to just use InjectionTokens to allow the user to provide their own value. There could be some utility APIs such as  `provideNgDocRepository()` to offer a type-safe customization experience.

**Comment by skoropadas** [comment]
The ability to use JavaScript for the configuration file should be supported I will check and fix it if there's an issue.

Regarding the configuration file itself, you're absolutely right. It only configures the builder's operation and how it generates documentation. Previously, its configuration was part of `angular.json` but was moved to a separate file because the builder learned to accept custom functions imported from libraries (for example, for Keywords loaders). I am also considering a plugin system for the builder to have control over what the builder generates, so I decided to move away from using `angular.json` to make it easier to create and configure features.

Additionally, anything related to the application itself or UI components is configured using tokens, for example, using the `provideNgDocApp` function as you suggested.

**Comment by TheNightmareX** [comment]
Makes sense. I suggest to make it more clear in the documentation that the configuration is for the building process. I was a bit confused about the role of the configuration file at my first glance.

Would love to help with the documentation.
