### ISSUE TITLE
[Feature] Support template variables for inputs

### ISSUE THREAD

**Issue by rubenprins** [ng-doc/ng-doc#156]
### Description

We have some components we'd like to showcase that have a template variable referencing another component or DOM element:
```html
<button [toggleHiddenFor]="panel">
  Toggle panel
</button>
<div #panel hidden>
  ...
</div>
```
However, there does not appear to be a way to configure your playground in that way, because template variables are not really a thing there?

Specifying `<button [toggleHiddenFor]="panel">` in the playground template doesn't work.

### Proposed solution

One way of fixing this could be to allow specifying literal inputs in the playground templates, and and automatically adding them to `hiddenInputs`.

### Alternatives considered

Another way to handle this would be to extend `inputs`:
```ts
template: `
  <button toggleHiddenFor>Toggle</button>
  <div #panel hidden>
    ...
  </div>
`,
inputs: {
  elementToToggle: templateVariable('panel'), // returns instance of internal, special-cased class
},
```

**Comment by skoropadas** [comment]
I would say it's a bug because it should work, ngdoc builds angular template based on the template string, so angular syntax must work, I'll check and fix it, thanks!

**Comment by skoropadas** [comment]
Ah, I see, the problem is that it's being passed into the input that the playground is trying to recognize. If I add the ability to ignore certain inputs for the playground, will that solve your problem?

**Comment by rubenprins** [comment]
I'm not sure? Are you saying the reason this doesn't work right now (the inputs in the template are just gone after rendering), is because they're overwritten by input overrides/defaults, regardless of their template values, and then stripped because they have a default value?

If that's the case, and the "ignore these inputs for ng-doc template binding and leave them to Angular" would probably be what I need.

A simple test would be to allow the ng-doc icon demo to set the size or color input in the template and then ignore it in the playground setup, right?

**Comment by skoropadas** [comment]
The problem is that ngdoc defines toggleHiddenFor as an input, and for all inputs, ngdoc tries to determine the type and create a special control in the sidebar. It also binds the sidebar to the input of your component, thus overriding what you set in the template. So, the first option that came to mind is to create an exception list, where you could specify which inputs should not be bound and allow you to set its value in the template.

**Comment by rubenprins** [comment]
Got it. I'd be willing to test that PR out, if it's not too much work for you. Or tinker with the code myself to see if that works, if you can give me a pointer.

**Comment by skoropadas** [comment]
That'd be great! I'll let you know when PR is ready

**Comment by skoropadas** [comment]
Hey, in the new version, the issue should be fixed without any additional configuration required. I've decided that the builder itself can determine which inputs you've used in the template and can ignore them for playgrounds.

It seems to me that if you're passing a reference to an element or setting a value using Angular template syntax, generating a control for management in the sidebar is unnecessary. Because for setting default values for control, there's already another functionality in place.

So pls let me know how it works.

**Comment by rubenprins** [comment]
There appears to be a bug when you use the component's attribute selector: the RotatorPlayground now gives a "Cannot read properties of undefined (reading 'length')" error when you change the template to `<button [ngDocRotator]="true">Button</button>`.

**Comment by skoropadas** [comment]
@rubenprins good catch, it was an old bag in my parser, it's gonna be fixed in the new version, I'll also add some tests for it later because it's quite an important part of the library.

**Comment by rubenprins** [comment]
@skoropadas Looks to be fixed indeed. Thanks!
