### ISSUE TITLE
[Bug] Unable to leverage Keywords to create custom links in a reusable macro template

### ISSUE THREAD

**Issue by akhileshThapliyal** [ng-doc/ng-doc#162]
### Is this a regression?

No

### Description

I have a design requirement where I want to build box tiles in a fashion where I can link to another page. The tile will consist of a Title, Subtitle, icon images and link (connecting to an ng doc page). I want to use Keywords to generate the link within my 

**Current Behaviour**: When I use `*CustomAngularComponentPage` in an anchor tag within the macro it gives an output of NAN.

**Expected Behaviour**: I should be able to create custom macro widgets which can accept links. The reason I want to leverage Keywords is because it is easy to update the links when the page moves from one category to another.

https://github.com/akhileshThapliyal/my-ng-doc-app

I have checked the code in my playground repo, you can investigate the keyword-link page under /src/app folder. Please let me know if you require any further details.

### Sample Macro and the calling function

{% macro createBoxWithLink(title, description, keyword_link) %}
<div class="square">
    <p>{{ title }}</p>
    <p>{{ description }}</p>
    <a href="{{keyword_link}}">Macros Custom Link</a>
</div>
{% endmacro %}

{{ createBoxWithLink('Ng Doc', 'NgDoc is a library for creating documentation for your Angular projects, it is injected into the build process of a regular Angular application and creates documentation that can be displayed in it.', `*CustomAngularComponentPage`) }}

### Image showing the error

<img width="1075" alt="image" src="https://github.com/ng-doc/ng-doc/assets/7280745/7edf540e-127f-46aa-8df9-140baff8dc5a">

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

20.9.0

### Anything else?

Ng Doc version: 17.6.10

**Comment by skoropadas** [comment]
No, this will not work that way.
To help you better understand what is happening, I'll describe the working principle:

- First, NgDoc renders your markdown file using Nunjucks, thus calling all macros, functions, etc., to obtain the final markdown file.
- Then the markdown file is transformed into HTML.
- After that, post-processing starts, during which all used keywords will be replaced with links. NgDoc checks for keywords in all inline codes and code blocks.

Therefore, you are getting NAN because `*CustomAngularComponentPage` is not an available variable; it is simply a string value that will be replaced at the post-processing stage.

### Solution:
As a solution to the problem, you can change your code as follows:

```twig
{% macro createBoxWithLink(title, description, keyword_link) %}
<div class="square">
    <p>{{ title }}</p>
    <p>{{ description }}</p>
    `{{keyword_link}}`
</div>
{% endmacro %}

{{ createBoxWithLink('Ng Doc', 'NgDoc is a library for creating documentation for your Angular projects, it is injected into the build process of a regular Angular application and creates documentation that can be displayed in it.', '*CustomAngularComponentPage') }}
```

So you just need to provided keywords as a string, and render inside of inline code. This way, the string `{{keyword_link}}` will be transformed into inline code and replaced with a link at the post-processing stage.

**Comment by skoropadas** [comment]
Ah, I see, it's happening because there is no space between `div` and the used keyword, it is known behavior of the `marked` library that is used under the hood, so if you add a space, then it should start working:

```twig
{% macro createBoxWithLink(title, description, keyword_link) %}
<div class="square">
    <p>{{ title }}</p>
    <p>{{ description }}</p>
</div>

`{{keyword_link}}`
{% endmacro %}
```

But then you'll have another problem, markdown syntax is not supported inside HTML nodes, so if you try to put your keyword into the `div` you'll face the same issue. As a workaround, you can use the `code` tag, which is the HTML definition of inline code.

```twig
{% macro createBoxWithLink(title, description, keyword_link) %}
<div class="square">
    <p>{{ title }}</p>
    <p>{{ description }}</p>
    <code>{{ keyword_link }}</code>
</div>
{% endmacro %}
```

**Comment by skoropadas** [comment]
But the thing that you are trying to achieve using `createClicklableBoxTile` is not supported atm.

**Comment by akhileshThapliyal** [comment]
> But the thing that you are trying to achieve using `createClicklableBoxTile` is not supported atm.

Is there a workaround? Is it possible to access APIs which can provide the link path based on the keywords either in macros or from angular custom components? If not, I have to use hardcoded paths for the links and change them whenever used when the category changes for a page :(

**Comment by akhileshThapliyal** [comment]
> ```
> <code>{{ keyword_link }}</code>
> ```

Thank you so much the suggested solution works :)

**Comment by akhileshThapliyal** [comment]
> Ah, I see, it's happening because there is no space between `div` and the used keyword, it is known behavior of the `marked` library that is used under the hood, so if you add a space, then it should start working:
> 
> ```
> {% macro createBoxWithLink(title, description, keyword_link) %}
> <div class="square">
>     <p>{{ title }}</p>
>     <p>{{ description }}</p>
> </div>
> 
> `{{keyword_link}}`
> {% endmacro %}
> ```
> 
> But then you'll have another problem, markdown syntax is not supported inside HTML nodes, so if you try to put your keyword into the `div` you'll face the same issue. As a workaround, you can use the `code` tag, which is the HTML definition of inline code.
> 
> ```
> {% macro createBoxWithLink(title, description, keyword_link) %}
> <div class="square">
>     <p>{{ title }}</p>
>     <p>{{ description }}</p>
>     <code>{{ keyword_link }}</code>
> </div>
> {% endmacro %}
> ```

Thank you so much the suggested solution works :)

**Comment by skoropadas** [comment]
> Is there a workaround?

No unfortunately, keywords are not available on the nunjucks side, because list of keywords are actually created based on nunjucks and markdown output, so it's just not possible.

**Comment by akhileshThapliyal** [comment]
> > Is there a workaround?
> 
> No unfortunately, keywords are not available on the nunjucks side, because list of keywords are actually created based on nunjucks and markdown output, so it's just not possible.

No problem, I was able to achieve it by leveraging the code tag and having an absolute position of the anchor tag occupying the complete width of the tile :)
