### ISSUE TITLE
[Bug] Unable to build docs when Playground refers components from angular library

### ISSUE THREAD

**Issue by akhileshThapliyal** [ng-doc/ng-doc#166]
### Is this a regression?

No

### Description

When I try to use a component from the angular library in the playground it throws an error "An unhandled exception occurred: Invalid target class for playground "TagPlayground". Make sure that the class is decorated with @Component, @Directive or @Pipe."

**Current Behaviour**: When I try to include NgDocTagComponent from @ng-doc/ui-kit as stated in the example on the ng doc website (https://ng-doc.com/docs/guides/playground), it throws an error. However, if I use a local component from the application, it works fine.

<img width="1023" alt="image" src="https://github.com/ng-doc/ng-doc/assets/7280745/a8cee4df-b32f-4a58-a3bb-c032ef3bd4c3">

**Expected Behavior**: I should be able to leverage components from angular libraries in the playground.

Github Repo: https://github.com/akhileshThapliyal/my-ng-doc-app

### ng-doc-tag/ng-doc.page.ts
```typescript
import {NgDocPage} from '@ng-doc/core';
import { NgDocTagComponent } from '@ng-doc/ui-kit';

const NgDocTagPage: NgDocPage = {
	title: `Ng Doc Tag`,
	mdFile: './index.md',
	demos: { NgDocTagComponent },
	imports: [
		NgDocTagComponent
	],
	playgrounds: {
		TagPlayground: {
		  target: NgDocTagComponent,
		  template: `<ng-doc-selector>Tag Label</ng-doc-selector>`,
		},
	  },
};

export default NgDocTagPage;
``` 
### ng-doc-tag/index.md

```typescript
# {{ NgDocPage.title }}

It's time to write some awesome docs!

{{ NgDocActions.playground("TagPlayground") }}
``` 

### Please provide the exception or error you saw

```true
⠋ NgDoc: Building...An unhandled exception occurred: Invalid target class for playground "TagPlayground". Make sure that the class is decorated with @Component, @Directive or @Pipe.
```

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

20.9.0

### Anything else?

Ng Doc Version: 17.6.10

**Comment by skoropadas** [comment]
Yes, it's a known limitation of playgrounds and the API generator, I'll add it to documentation. To create a playground and recognize inputs NgDoc needs the source code, it can't read this information from dts and compiled code.

**Comment by skoropadas** [comment]
But I'll recheck it, maybe there's a way to load this information

**Comment by skoropadas** [comment]
Okay, I looked at the code and unfortunately, it is not possible to implement. The source code of the component for the playground must be located inside the documentation repository. The main reason it is not possible to build playgrounds based on compiled code is due to decorators.

NgDoc uses information from component, directive, and pipe decorators to correctly generate the playground. Decorators are a TypeScript feature and they do not exist in the compiled JS, so I simply have no way to obtain this information.

So I am closing this ticket because at the moment it's just impossible to implement.
