### ISSUE TITLE
[Bug] `@remarks` tag support in description

### ISSUE THREAD

**Issue by AdrianKokot** [ng-doc/ng-doc#218]
### Is this a regression?

I don't know

### Description

In #10 there's information that "NgDoc will join summary section with remark section":

> I would suggest to use this tag, NgDoc will join summary section with remark section of the doc because there is no need to split them at the moment, but in the future they could be displayed sepparatly on different tabs of the API page or smth like that

As I understand this should work, but from what I've tested, the text from `@remarks` tag is not rendered in API Reference.

I agree that there's no need to split `@remarks` from summary, so I'd suggest improving `getJsDocDescription` function to return also `@remarks` tags. I think small addon could be "Notes" header after description and before remakrs, same as in IDE ts-doc preview:

![image](https://github.com/user-attachments/assets/4ae50d91-de54-45b1-bbb6-0613ab228b28)

### OS

Windows

### Browser

None

### Node version

20.14.0

**Comment by AdrianKokot** [comment]
@skoropadas I can work on it, but I would like some clarification on why it was described as working, and it doesn't - am I doing something wrong, or did it work in the past, and now it doesn't, or what is the case?

Also, which approach would be better from your point of view, extending function for getting description or extending njuncks templates?

**Comment by skoropadas** [comment]
It's hard to say. I created the ticket when I released the first version, so I might have made a mistake since I definitely didn't add support for `remarks`.

I believe the simplest solution is to extend `libs/builder/templates/api/base.html.nunj`, which is used for all API templates. This way, you can add support for `remarks` across all API renderings but don't forget to add `hideRemarks` variable and use it in `libs/builder/engine/nunjucks/actions/api.action.ts` it's responsible for the API rendering in guides.

And thanks a lot for all your support, I highly appreciate it especially now when I don't have to much time to work on the library! ❤️

**Comment by AdrianKokot** [comment]
@skoropadas What do you think about this kind of styling?:
![image](https://github.com/user-attachments/assets/803d8c07-5a9a-4852-9021-d9f12636829d)

Generated from:
```typescript
/**
 * Page configuration interface, that should be used to describe configuration of the page
 *
 * @remarks Test remark 1
 * @remarks Test remark 2
 * @remarks
 * Test block remark line 1
 * Test block remark line 2
 *
 * Test block remark line 3
 */
```

**Comment by skoropadas** [comment]
Looks good 👍🏻 But I would apply the same heading level and style as used for the "Usage Notes"

**Comment by AdrianKokot** [comment]
Hm… can do that, but I decided to use smaller level as remarks is kind of part of description, but maybe you're right. Will use the same level and create PR
