### ISSUE TITLE
[Bug] Table of content anchor doesn't work properly

### ISSUE THREAD

**Issue by Nxtivision** [ng-doc/ng-doc#74]
### Is this a regression?

I don't know

### Description

# Description of the problem
It seems we are not able to use anchors in our table of content inside Markdown.

## Current behavior
Here are two examples:
```markdown
- [Installer la librairie](#installer-la-librairie)
```
--> Redirect to root page (/)
```markdown
- [Installer la librairie](/getting-started/installation#installer-la-librairie)
```
--> Do nothing

## Expected behavior
We should have a smooth scroll directly on the concerned title.
The best would be to only specify the fragment like `#installer-la-librairie` and it uses the current route, instead of specifying the base route each time.

Thank you in advance :)

### OS

Windows

### Browser

Chrome

### Node version

18.16.0

**Comment by skoropadas** [comment]
Hi, thanks for the bug report, have you tried using the keyword feature to create links? I'm just wondering if this will work for you or not

**Comment by Nxtivision** [comment]
Thank you for your anwser, I just tried the keyword feature like that:
```markdown
`*GettingStartedInstallation#Installer-La-Librairie`
```
```typescript
// in ng-doc.page.ts
{
...
  keyword: 'GettingStartedInstallation',
}
```
It generates my link:
![2023-07-03_14h09_40](https://github.com/ng-doc/ng-doc/assets/89700030/2964b15e-c897-454d-a373-a21a54e31b86)

However, when I click on it, the URL is correctly set but the scroll on the current page has not been performed

**Comment by skoropadas** [comment]
Yep that's my bad, sorry I forgot to add this to documentation. Scroll to the anchor is not handled by the NgDoc, to enable it, you need to configure your `RouterModule`, e.g. like this:

```ts
RouterModule.forRoot([]
  {
    scrollPositionRestoration: 'enabled',
    anchorScrolling: 'enabled',
    scrollOffset: [0, 70],
  },
),
```

**Comment by Nxtivision** [comment]
And it works correctly now 🚀 
FYI, here is the way for Standalone approach, inside the `app.config.ts`
```typescript
...(RouterModule.forRoot(routes, {
      scrollPositionRestoration: 'enabled',
      anchorScrolling: 'enabled',
      scrollOffset: [0, 70],
    }).providers || []),
```
I had to do this because they unfortunately do not provide `scrollOffset` with the following way:
```typescript
provideRouter(
  routes,
  withInMemoryScrolling({
    scrollPositionRestoration: 'enabled',
    anchorScrolling: 'enabled',
    //scrollOffset: [0, 70], // no such option available now
  })
)
```

**Comment by skoropadas** [comment]
great, yeah it's hard times for library maintainers with all these differences between standalone and non-standalone apps 😄

In any case, I advise you to use keywords because they are more dynamic and validated during documentation compilation. If necessary, I can also add a way to configure the generation of the link label if the current format does not suit you.

Regarding the bug - This is the standard behavior of rendering Markdown to HTML, and I would prefer not to change it. As far as I understand, you are creating a table of contents within the page, but I don't fully understand why, as it is automatically generated for each page and displayed on the right side of the screen.

Anyway, I will keep this ticket as a reminder to add scrolling configuration to the manual setup in the documentation.

**Comment by Nxtivision** [comment]
Oh my... You're right. I've noticed the quick nav on the right side. 
I'm so busy migrating our documentation between Storybook and NgDoc, that I forgot that this feature is natively planned
😁 

I will keep keywords and work with them, and I can provide you a feedback after 😉

**Comment by skoropadas** [comment]
awesome thank you! 👍
