### ISSUE TITLE
[Feature] correct name when generating category/page with schematics

### ISSUE THREAD

**Issue by Nxtivision** [ng-doc/ng-doc#75]
### Description

At the moment, when I create a category/page using some `/`, the generated exported `const` name is wrong.

For example:
`nx generate @ng-doc/builder:category --title=04-one/theme --order=0 --path=apps/public-doc/src --route=one-theme`
will create a category with name:
`const 04One/themeCategory`

### Proposed solution

In such cases, it could be interesting to only keep the last fragment of the title, so the directories still get correctly generated and the title will be corrected also

### Alternatives considered

No use of `/` but if we can have an easier life... :)

**Comment by skoropadas** [comment]
Actually, I think the working principle of the `title` parameter is not entirely correct at the moment. The schematic generates the variable name based on the `title`, but this won't work for all cases. For example, in your case or if the `title` contains non-Latin letters, such as Cyrillic or other forbidden characters in variable names. That's why I would probably consider how to eliminate this issue.

I have a couple of ideas. The first one is a solution for your problem and the one I described earlier. I could add an additional parameter for the variable name so that you can invoke the schematic like this:

```
nx generate @ng-doc/builder:category --name=theme --title=04-one/theme --order=0 --path=apps/public-doc/src --route=one-theme
```

However, I'm not happy with it as it looks complicated.

The second solution, which I started thinking about a couple of weeks ago, involves using special functions. In fact, they will be empty and return the configuration object as is. They will only be needed for type checking. With this solution, the generated page file would look like this:

```javascript
import { page } from '@ng-doc/core';

export default page({
  title: 'my-title',
  mdFile: './index.md',
});
```

It looks simpler to me, without additional variables, and it won't cause any breaking changes. Meanwhile, you will be able to use the schematic command like this:

```
nx generate @ng-doc/builder:category --title=theme --order=0 --path=apps/public-doc/src/04-one --route=one-theme
```

**Comment by Nxtivision** [comment]
In one of our libraries, we also started using object like you, but we will also switch to function for efficiency. So I will agree with the principle of your second solution.

So, if I summarize your point:
* Switch exported configuration object to exported default function
* Separate the behavior of the property `title` so it is used only for the configuration of NgDoc and not for creating the whole path with sub-directories
* The `path` property provisioned inside the CLI will generate all directories and sub-directories correctly

I completely agree 👍

**Comment by skoropadas** [comment]
Yes, this pattern will be applied to all types of files you listed. I will also add a migration to transition existing code to the new format. While this feature won't break anything, I believe nobody wants to manually update old configurations to the new format. 😄

**Comment by skoropadas** [comment]
@Nxtivision I encountered a problem when trying to build the application in production mode. It appears that I cannot use this pattern of exporting a function call because the Angular compiler cannot analyze the components and modules that you are using as targets for playgrounds, demos, and in the `imports` field. This is because the compiler expects static values, while a function call returns a dynamic value. Attempts to make the accepted configuration static using `as const` or `readonly` did not succeed.

I could reimport these entities into the generated files, but I'm concerned that it might cause problems in the future. Therefore, I have to roll back these changes and possibly use transliteration because even the approach with `satisfies` does not work. It seems that the Angular compiler does not support it:

```ts
import { NgDocPage } from '@ng-doc/core';
import { NgDocTagComponent } from '@ng-doc/ui-kit';

export default {
	title: `Page`,
	mdFile: './index.md',
	playgrounds: {
		TagPlayground: {
			target: NgDocTagComponent,
			template: `<ng-doc-selector>Tag</ng-doc-selector>`,
		},
	},
} satisfies NgDocPage;
```
