### ISSUE TITLE
[Feature] Playground should recognize value from InjectionToken

### ISSUE THREAD

**Issue by Nxtivision** [ng-doc/ng-doc#76]
### Description

Inside a playground, I have a component called `OneAlertComponent`:
```typescript
const AlertPage: NgDocPage = {
  title: `Alert`,
  mdFile: './index.md',
  category: OneThemeCategory,
  order: 2,
  imports: [OneAlertModule],
  providers: [provideOneAlertDefaultOptions()],
  playgrounds: {
    AlertPlayground: {
      target: OneAlertComponent,
      template: `
        <one-alert>
          <one-alert-title>Titre de l'alert</one-alert-title>
          <one-alert-content>Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.</one-alert-content>
        </one-alert>
      `,
    },
  },
};
```

Inputs inside this component are filled via default values from an InjectionToken like this:
```
private defaultOptions = inject(ONE_ALERT_DEFAULT_OPTIONS);

@Input()
type: OneAlertType = this.defaultOptions.type; // the default value will be 'default'
```
`OneAlertType: Alias for: "default" | "success" | "error" | "info" | "warning"`

However, it does not set the value as expected. I also tried:

`type: OneAlertType = this.defaultOptions.type || 'default';` in case it didn't find `this.defaultOptions` or set it to `undefined`, but nothing. The only way to have the correct value set for Playground is the static value `'default'`.

### Proposed solution

We have 2 options:
* Either we can dynamically read the value of the input (read directly via the injection token, if applicable)
* Or we can have a new property for `inputs`, where we can set directly the inputs manually

What do you think ?

### Alternatives considered

/

**Comment by skoropadas** [comment]
Yes, I am aware of this limitation. I was thinking about it when I was writing this feature, but at that time, I couldn't come up with a good solution.

Give me some time to review the code again and think about a possible solution. Perhaps now I can do better. I think your suggestion with the "inputs" field might work. That way, you could predefine default values, but I still want to automate it without any additional actions from the user.

Currently, it doesn't work for some default values because the value is directly read from the code as a string, and then NgDoc tries to convert it into a real value. Since there is no Angular context in the execution context, the values from the service simply cannot be read. But I think I could try moving the logic related to default values to the application itself rather than the builder. I could create a component, read the values of the @Input fields, and then initialize the playground with the form. This might work, but I need some time for that.

**Comment by skoropadas** [comment]
Just a quick update: I found a solution, I'll try to release it today :)

**Comment by Nxtivision** [comment]
I can confirm it works as expected! 👍
