### ISSUE TITLE
[Bug] Component not building after updating to 16.12.0

### ISSUE THREAD

**Issue by Nxtivision** [ng-doc/ng-doc#99]
### Is this a regression?

Yes

### Description

Hello,

Sorry but once I update the project with the new version (16.12.0) containing the new feature explained in #97, it doesn't work anymore 🤔 
[in the same repository](https://nxtivision-ngdocsandbox-vvwt74pm7to.ws-eu104.gitpod.io/), I just updated my `package.json` and I have the following issue:

```
NgDoc: 1 entities with problems:
✖   src/app/docs/issue-96/ng-doc.page.ts:
✖     TypeError: Cannot read properties of undefined (reading 'ɵfac')
✖     TypeError: Cannot read properties of undefined (reading 'ɵfac')
```

Any idea ?

### Please provide the exception or error you saw

```true
NgDoc: 1 entities with problems:
✖   src/app/docs/issue-96/ng-doc.page.ts:
✖     TypeError: Cannot read properties of undefined (reading 'ɵfac')
✖     TypeError: Cannot read properties of undefined (reading 'ɵfac')
```

### OS

Windows

### Browser

Chrome

### Node version

18.16.0

**Comment by skoropadas** [comment]
Hey, thanks for the ticket, I'll try to fix it today!

**Comment by skoropadas** [comment]
I have released a fix, but I also want to explain what the problem is so that you understand the possible ways to use your mixins.

NgDoc compiles files like `ng-doc.page.ts`, `ng-doc.category.ts`, etc. using `esbuild` to load and read them later, in order to speed up the compilation and subsequent loading process. It removes some fields in files like `ng-doc.page.ts` before compilation, which may reference Angular packages or have multiple dependencies. For example, the `target` field in the playground. These fields are not needed by NgDoc to generate Angular components (in the `.ng-doc` folder). They are only needed for static reading and defining their API, as well as subsequent loading on the application side. In your case, NgDoc did not remove the `data` property that referenced `FormControl`, which is why you encountered a similar error.

Regarding the use of the `control` field, you can statically define a list of controls, but you can also do it dynamically based on your MIXIN_METADATA_CVA_CONNECTOR variable.
For example like this:

```typescript
controls: {
        ...MIXIN_METADATA_CVA_CONNECTOR.inputs.reduce((acc, curr) => {
          // if they all have a string type
          acc[curr] = 'string';

          return acc;
        }, {} as Record<string, string>),
      },
```

However, in that case, you need to move it to a separate file that does not contain imports from `@angular/*`, because otherwise, `esbuild` will include these files in the compiled result of the `ng-doc.page.ts` file, and NgDoc won't be able to dynamically load it to read the necessary properties due to properties that do not exist within the Node.js environment (`'ɵfac'` as in your case).

**Comment by Nxtivision** [comment]
Thank you, I tried the fix and it works like a charm! I also followed your advice and changed it a little bit: I've just created a file called `controls.ts` at the root of this category, where I have created the different controls statically, like this, they will be no unnecessary imports inside the esbuild compiler 😉

**Comment by skoropadas** [comment]
Nice! I will release a new version soon, which will allow imports from files with Angular dependencies, but this will force you to additionally import @angular/compiler to get rid of the error that you encountered. This may affect performance, but in any case you will have options to choose from.
